// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: proto/v2/resolve.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveResponse_Entity_Status int32

const (
	ResolveResponse_Entity_UNKNOWN_STATUS ResolveResponse_Entity_Status = 0
	ResolveResponse_Entity_COMPLETED      ResolveResponse_Entity_Status = 1
	ResolveResponse_Entity_FAILED         ResolveResponse_Entity_Status = 2
)

// Enum value maps for ResolveResponse_Entity_Status.
var (
	ResolveResponse_Entity_Status_name = map[int32]string{
		0: "UNKNOWN_STATUS",
		1: "COMPLETED",
		2: "FAILED",
	}
	ResolveResponse_Entity_Status_value = map[string]int32{
		"UNKNOWN_STATUS": 0,
		"COMPLETED":      1,
		"FAILED":         2,
	}
)

func (x ResolveResponse_Entity_Status) Enum() *ResolveResponse_Entity_Status {
	p := new(ResolveResponse_Entity_Status)
	*p = x
	return p
}

func (x ResolveResponse_Entity_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResolveResponse_Entity_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v2_resolve_proto_enumTypes[0].Descriptor()
}

func (ResolveResponse_Entity_Status) Type() protoreflect.EnumType {
	return &file_proto_v2_resolve_proto_enumTypes[0]
}

func (x ResolveResponse_Entity_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResolveResponse_Entity_Status.Descriptor instead.
func (ResolveResponse_Entity_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_v2_resolve_proto_rawDescGZIP(), []int{1, 0, 0}
}

// Three modes are supported:
//
//  1. ID to ID:
//     nodes = ["wikidataId/CA", "wikidataId/MA"]
//     property = "<-wikidataId->nutsCode"
//
//  2. Coordinate (latitude#longitude) to DCID:
//     nodes = ["34.56#-23.12", "-22.11#44.55"]
//     property = "<-geoCoordinate->dcid"
//
//  3. Description (name) to DCID:
//     nodes = ["Mountain View", "New York"]
//     property = "<-description->dcid" or "<-description{typeOf:City}->dcid"
type ResolveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes               []string         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Property            string           `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"` // Deprecated: Use specialized_resolver and filters instead.
	SpecializedResolver string           `protobuf:"bytes,3,opt,name=specialized_resolver,json=specializedResolver,proto3" json:"specialized_resolver,omitempty"`
	SearchProperties    []string         `protobuf:"bytes,4,rep,name=search_properties,json=searchProperties,proto3" json:"search_properties,omitempty"`
	Filters             *structpb.Struct `protobuf:"bytes,5,opt,name=filters,proto3" json:"filters,omitempty"`
	Limit               *int32           `protobuf:"varint,6,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	ReturnedProperties  []string         `protobuf:"bytes,7,rep,name=returned_properties,json=returnedProperties,proto3" json:"returned_properties,omitempty"`
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_resolve_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_resolve_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_resolve_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveRequest) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ResolveRequest) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

func (x *ResolveRequest) GetSpecializedResolver() string {
	if x != nil {
		return x.SpecializedResolver
	}
	return ""
}

func (x *ResolveRequest) GetSearchProperties() []string {
	if x != nil {
		return x.SearchProperties
	}
	return nil
}

func (x *ResolveRequest) GetFilters() *structpb.Struct {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ResolveRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ResolveRequest) GetReturnedProperties() []string {
	if x != nil {
		return x.ReturnedProperties
	}
	return nil
}

type ResolveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities []*ResolveResponse_Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_resolve_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_resolve_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_proto_v2_resolve_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveResponse) GetEntities() []*ResolveResponse_Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type ResolveResponse_Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node       string                              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Candidates []*ResolveResponse_Entity_Candidate `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Status     ResolveResponse_Entity_Status       `protobuf:"varint,4,opt,name=status,proto3,enum=datacommons.v2.ResolveResponse_Entity_Status" json:"status,omitempty"`
	Error      string                              `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ResolveResponse_Entity) Reset() {
	*x = ResolveResponse_Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_resolve_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveResponse_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse_Entity) ProtoMessage() {}

func (x *ResolveResponse_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_resolve_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse_Entity.ProtoReflect.Descriptor instead.
func (*ResolveResponse_Entity) Descriptor() ([]byte, []int) {
	return file_proto_v2_resolve_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ResolveResponse_Entity) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ResolveResponse_Entity) GetCandidates() []*ResolveResponse_Entity_Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *ResolveResponse_Entity) GetStatus() ResolveResponse_Entity_Status {
	if x != nil {
		return x.Status
	}
	return ResolveResponse_Entity_UNKNOWN_STATUS
}

func (x *ResolveResponse_Entity) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ResolveResponse_Entity_Candidate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dcid         string           `protobuf:"bytes,1,opt,name=dcid,proto3" json:"dcid,omitempty"`
	DominantType string           `protobuf:"bytes,2,opt,name=dominant_type,json=dominantType,proto3" json:"dominant_type,omitempty"`
	Name         string           `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Properties   *structpb.Struct `protobuf:"bytes,4,opt,name=properties,proto3" json:"properties,omitempty"`
	Metadata     *structpb.Struct `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TypeOf       []string         `protobuf:"bytes,6,rep,name=type_of,json=typeOf,proto3" json:"type_of,omitempty"`
}

func (x *ResolveResponse_Entity_Candidate) Reset() {
	*x = ResolveResponse_Entity_Candidate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v2_resolve_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveResponse_Entity_Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse_Entity_Candidate) ProtoMessage() {}

func (x *ResolveResponse_Entity_Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_resolve_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse_Entity_Candidate.ProtoReflect.Descriptor instead.
func (*ResolveResponse_Entity_Candidate) Descriptor() ([]byte, []int) {
	return file_proto_v2_resolve_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *ResolveResponse_Entity_Candidate) GetDcid() string {
	if x != nil {
		return x.Dcid
	}
	return ""
}

func (x *ResolveResponse_Entity_Candidate) GetDominantType() string {
	if x != nil {
		return x.DominantType
	}
	return ""
}

func (x *ResolveResponse_Entity_Candidate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolveResponse_Entity_Candidate) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ResolveResponse_Entity_Candidate) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ResolveResponse_Entity_Candidate) GetTypeOf() []string {
	if x != nil {
		return x.TypeOf
	}
	return nil
}

var File_proto_v2_resolve_proto protoreflect.FileDescriptor

var file_proto_v2_resolve_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x32, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x32, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x02, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x64,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x31, 0x0a, 0x14, 0x73,
	0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x73, 0x70, 0x65, 0x63, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x12, 0x2b,
	0x0a, 0x11, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x07, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x19,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x13, 0x72, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x12, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x65, 0x64,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0xc4, 0x04, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x1a, 0xec, 0x03, 0x0a,
	0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x50, 0x0a, 0x0a, 0x63,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x30, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x32,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x0a, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x45, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0xdf, 0x01, 0x0a, 0x09, 0x43,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x63, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x63, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d,
	0x64, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x33,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6f, 0x66, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x4f, 0x66, 0x22, 0x37, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f,
	0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49,
	0x4c, 0x45, 0x44, 0x10, 0x02, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x42, 0x33, 0x5a, 0x31, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x6f, 0x72, 0x67, 0x2f, 0x6d, 0x69, 0x78, 0x65, 0x72, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x32,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v2_resolve_proto_rawDescOnce sync.Once
	file_proto_v2_resolve_proto_rawDescData = file_proto_v2_resolve_proto_rawDesc
)

func file_proto_v2_resolve_proto_rawDescGZIP() []byte {
	file_proto_v2_resolve_proto_rawDescOnce.Do(func() {
		file_proto_v2_resolve_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v2_resolve_proto_rawDescData)
	})
	return file_proto_v2_resolve_proto_rawDescData
}

var file_proto_v2_resolve_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v2_resolve_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_v2_resolve_proto_goTypes = []interface{}{
	(ResolveResponse_Entity_Status)(0),       // 0: datacommons.v2.ResolveResponse.Entity.Status
	(*ResolveRequest)(nil),                   // 1: datacommons.v2.ResolveRequest
	(*ResolveResponse)(nil),                  // 2: datacommons.v2.ResolveResponse
	(*ResolveResponse_Entity)(nil),           // 3: datacommons.v2.ResolveResponse.Entity
	(*ResolveResponse_Entity_Candidate)(nil), // 4: datacommons.v2.ResolveResponse.Entity.Candidate
	(*structpb.Struct)(nil),                  // 5: google.protobuf.Struct
}
var file_proto_v2_resolve_proto_depIdxs = []int32{
	5, // 0: datacommons.v2.ResolveRequest.filters:type_name -> google.protobuf.Struct
	3, // 1: datacommons.v2.ResolveResponse.entities:type_name -> datacommons.v2.ResolveResponse.Entity
	4, // 2: datacommons.v2.ResolveResponse.Entity.candidates:type_name -> datacommons.v2.ResolveResponse.Entity.Candidate
	0, // 3: datacommons.v2.ResolveResponse.Entity.status:type_name -> datacommons.v2.ResolveResponse.Entity.Status
	5, // 4: datacommons.v2.ResolveResponse.Entity.Candidate.properties:type_name -> google.protobuf.Struct
	5, // 5: datacommons.v2.ResolveResponse.Entity.Candidate.metadata:type_name -> google.protobuf.Struct
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_v2_resolve_proto_init() }
func file_proto_v2_resolve_proto_init() {
	if File_proto_v2_resolve_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_v2_resolve_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_resolve_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_resolve_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveResponse_Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v2_resolve_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveResponse_Entity_Candidate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_v2_resolve_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v2_resolve_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v2_resolve_proto_goTypes,
		DependencyIndexes: file_proto_v2_resolve_proto_depIdxs,
		EnumInfos:         file_proto_v2_resolve_proto_enumTypes,
		MessageInfos:      file_proto_v2_resolve_proto_msgTypes,
	}.Build()
	File_proto_v2_resolve_proto = out.File
	file_proto_v2_resolve_proto_rawDesc = nil
	file_proto_v2_resolve_proto_goTypes = nil
	file_proto_v2_resolve_proto_depIdxs = nil
}
